[build]
  publish = "."
  command = ""

[processing]
  skip_processing = false
[processing.css]
  bundle = false
  minify = true
[processing.js]
  bundle = false
  minify = true
[processing.html]
  pretty_urls = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[redirects]]
  from = "/oto-cekici"
  to = "/hizmetler/oto-cekici.html"
  status = 200

[[redirects]]
  from = "/oto-cekici.html"
  to = "/hizmetler/oto-cekici.html"
  status = 200

[[redirects]]
  from = "/cekici-arac-tasima"
  to = "/hizmetler/oto-cekici.html"
  status = 200

[[redirects]]
  from = "/oto-kurtarma"
  to = "/hizmetler/oto-kurtarma.html"
  status = 200

[[redirects]]
  from = "/oto-kurtarma.html"
  to = "/hizmetler/oto-kurtarma.html"
  status = 200

